CREATE TABLE "blockchain" (
	"height" integer PRIMARY KEY NOT NULL,
	"is_processed" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "offer_parameters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "offer_parameters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"value" varchar(50) NOT NULL,
	"type" varchar(10) DEFAULT 'String' NOT NULL,
	"offer_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "offers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "offers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"deployment_params" json DEFAULT '{}'::json NOT NULL,
	"cid" varchar(65) NOT NULL,
	"name" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "resources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"owner_address" varchar(100) NOT NULL,
	"credentials" json DEFAULT '{}'::json NOT NULL,
	"deployment_status" varchar(20) NOT NULL,
	"group_name" varchar(100) DEFAULT 'default' NOT NULL,
	"offer_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "offer_parameters" ADD CONSTRAINT "offer_parameters_offer_id_offers_id_fk" FOREIGN KEY ("offer_id") REFERENCES "public"."offers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_offer_id_offers_id_fk" FOREIGN KEY ("offer_id") REFERENCES "public"."offers"("id") ON DELETE no action ON UPDATE no action;